/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookedRouteImport } from './routes/booked'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as ProductManagementCoachingRouteImport } from './routes/product-management-coaching'
import { Route as ProductManagementMentoringRouteImport } from './routes/product-management-mentoring'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedRoute = BookedRouteImport.update({
  id: '/booked',
  path: '/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductManagementCoachingRoute =
  ProductManagementCoachingRouteImport.update({
    id: '/product-management-coaching',
    path: '/product-management-coaching',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductManagementMentoringRoute =
  ProductManagementMentoringRouteImport.update({
    id: '/product-management-mentoring',
    path: '/product-management-mentoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/partner': typeof PartnerRoute
  '/partnership': typeof PartnershipRoute
  '/product-management-coaching': typeof ProductManagementCoachingRoute
  '/product-management-mentoring': typeof ProductManagementMentoringRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/partner': typeof PartnerRoute
  '/partnership': typeof PartnershipRoute
  '/product-management-coaching': typeof ProductManagementCoachingRoute
  '/product-management-mentoring': typeof ProductManagementMentoringRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/booked': typeof BookedRoute
  '/partner': typeof PartnerRoute
  '/partnership': typeof PartnershipRoute
  '/product-management-coaching': typeof ProductManagementCoachingRoute
  '/product-management-mentoring': typeof ProductManagementMentoringRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/booked'
    | '/partner'
    | '/partnership'
    | '/product-management-coaching'
    | '/product-management-mentoring'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/booked'
    | '/partner'
    | '/partnership'
    | '/product-management-coaching'
    | '/product-management-mentoring'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/booked'
    | '/partner'
    | '/partnership'
    | '/product-management-coaching'
    | '/product-management-mentoring'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BookedRoute: typeof BookedRoute
  PartnerRoute: typeof PartnerRoute
  PartnershipRoute: typeof PartnershipRoute
  ProductManagementCoachingRoute: typeof ProductManagementCoachingRoute
  ProductManagementMentoringRoute: typeof ProductManagementMentoringRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked': {
      id: '/booked'
      path: '/booked'
      fullPath: '/booked'
      preLoaderRoute: typeof BookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-management-coaching': {
      id: '/product-management-coaching'
      path: '/product-management-coaching'
      fullPath: '/product-management-coaching'
      preLoaderRoute: typeof ProductManagementCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-management-mentoring': {
      id: '/product-management-mentoring'
      path: '/product-management-mentoring'
      fullPath: '/product-management-mentoring'
      preLoaderRoute: typeof ProductManagementMentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BookedRoute: BookedRoute,
  PartnerRoute: PartnerRoute,
  PartnershipRoute: PartnershipRoute,
  ProductManagementCoachingRoute: ProductManagementCoachingRoute,
  ProductManagementMentoringRoute: ProductManagementMentoringRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
